<Project>
    
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
		<NoWarn>IDE0021,IDE0290</NoWarn>
	</PropertyGroup>

    <!--
        IDE0021: Use expression body for constructor
        IDE0290: Use primary constructor
    -->
    
</Project>
